### ISSUE TITLE
Registry.getByID can result in a panic

### ISSUE THREAD

**Issue by andrejacobs** [anthdm/hollywood#10]
If the PIDSeparator is changed (lets say to ">") and a call to .getByID("foo/bar") is made then it results in a panic.

```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x20 pc=0x100a47368]
```

Easiest way to test is to change the registry_test/TestGetByName and change the PIDSeparator and or the getByID argument.

```
	PIDSeparator = ">"
...
	// local/foo/bar/q/1
	e.SpawnFunc(func(c *Context) {}, "foo", WithTags("bar", "q", "1"))
	time.Sleep(time.Millisecond * 10)
	proc = e.Registry.getByID("foo/bar/q/1")
```

**Comment by anthdm** [comment]
@andrejacobs  I see. Good catch. I think the Engine needs a config (we need this later for adding custom serializers) where they can specify the PIDSeparator. I think this is the cleanest solution, cause it is not allowed nor the intention to change those at "runtime".

**Comment by anthdm** [comment]
This is fixed in the beta. PID separators cannot be modified on runtime and need to be specified in the engine configuration.
