### ISSUE TITLE
Beatiful stack traces on actor panic

### ISSUE THREAD

**Issue by anthdm** [anthdm/hollywood#106]
Problem:
When an actor  (receiver) panics it dumps out the "normal" Go stack trace.

1. the stack contains unnecessary callers
2. its annoying

Solution:
Custom trace by parsing the given stack trace?

**Comment by perbu** [comment]
proposed dependency:

https://github.com/DataDog/gostackparse

It's a nice, simple package that parses stack traces. It makes is trivial to automate skipping frames which means we can clean up the trace and send it in a Event.

I'm not sure if hollywood should print the stack trace or leave it up the user to do this.
