### ISSUE TITLE
Not providing a region in cluster.Config cause panic

### ISSUE THREAD

**Issue by anthdm** [anthdm/hollywood#117]
Not providing a region should not panic the cluster.

**Comment by perbu** [comment]
general question; we can crash hollywood quite a bit by providing nil pointers here and there. is this something we wanna guard against? It'll mean quite a few guards at every entrypoint.

**Comment by anthdm** [comment]
@perbu correct. I have some guards around the nil engine and other fields in cluster now. We might want to double check in other constructors.

**Comment by perbu** [comment]
iirc engine.Send() crashes on a nil pid.

**Comment by anthdm** [comment]
@perbu that's a good one actually. I will patch that ASAP.
