### ISSUE TITLE
Can't build the example

### ISSUE THREAD

**Issue by cxytz01** [anthdm/hollywood#126]
Can't build this source file - https://github.com/anthdm/hollywood/blob/master/examples/helloworld/main.go
the build steps are:
1. go mod tidy
2. go build

responded to the error:
C:\Users\abc\go\pkg\mod\github.com\anthdm\hollywood@v0.0.0-20231223075317-ea56d2c2ff6b\actor\context.go:4:2: package log/slog is not in GOROOT (D:\Go\src\log\slog)

my Golang version is go1.20.2 windows/amd64

**Comment by anthdm** [comment]
@cxytz01 You will need Golang 1.21. We are using slog which is only available from 1.21 onward.
