### ISSUE TITLE
Consider having a clusterprovider which uses mdns.

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#134]
Service discovery by mdns seems useful. Within a network, having nodes in the same cluster automatically find each other solves a rather complex issue which would otherwise require consul or similar tooling.

See if we can have a cluster provider which uses mdns zeroconf.

**Comment by anthdm** [comment]
Good idea. This is in progress #135

**Comment by perbu** [comment]
hah. you're way to fast.
