### ISSUE TITLE
EngineConfig{Remote}

### ISSUE THREAD

**Issue by xtox-io** [anthdm/hollywood#150]
Remote is not public in EngineConfig.
```bash
make bench
```
is failing.

**Comment by xtox-io** [comment]
Oh also `nil` is used for `remote.Config`

**Comment by xtox-io** [comment]
That should be (sorry didn't have the time open a fix)

```bash
r := remote.New(fmt.Sprintf("localhost:%d", 4000+i), remote.Config{})
 e, err := actor.NewEngine(actor.NewEngineConfig().WithRemote(r))
```

**Comment by anthdm** [comment]
Good catch. The Bench is not included in the CI. :(

**Comment by xtox-io** [comment]
Thanks a lot for what you are doing :) Hope to meet you when it"s time :)
