### ISSUE TITLE
 The release tag "v1.0" does not work

### ISSUE THREAD

**Issue by rts-gordon** [anthdm/hollywood#158]
Hi @anthdm 

  The tag "v1.0" does not work, can you please add a new tag that scheme structured as x.y.z, like "v1.0.0". Thank you.

**Comment by anthdm** [comment]
@rts-gordon Merge a couple of PR right now and will make a new release `v1.0.1`

**Comment by BHare1985** [comment]
What is the status of this?

**Comment by anthdm** [comment]
Will make a new release today 🎈

**Comment by anthdm** [comment]
Fixed.
