### ISSUE TITLE
Cannot send remote messages, getting error panic: interface conversion: main.Message is not protoreflect.ProtoMessage: missing method ProtoReflect

### ISSUE THREAD

**Issue by webfrank** [anthdm/hollywood#165]
Hi,
  I have a simple test case with a two node cluster where I want to exchange a simple string.

I defined a message.proto like this:

```
syntax = "proto3";
package main;
option go_package = "./";

message Message {
    string data = 1;
}
```

and generated message.pb.go with

`protoc --go_out=. message.proto`

The resulting message.pb.go file has the method ProtoReflect:

```
...
func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_message_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
...
```

The same error I have with remote.TestMessage.

**Comment by anthdm** [comment]
The error you are encountering is because the message you are trying to send over the wire is not a Protobuf message. Can you share some more code or context so I can help you further?

**Comment by webfrank** [comment]
Hi, found the issue, I did not pass a pointer.
