### ISSUE TITLE
Releases/Versioning

### ISSUE THREAD

**Issue by rekram1-node** [anthdm/hollywood#19]
Are you planning on setting up a release pipeline so the library can have versioning? Not sure if you are waiting until after the alpha rollout or whatnot but whenever you do want it I could set it up for you if you would like. Super simple and EZ

**Comment by anthdm** [comment]
@rekram1-node sure man! I normally next commit should be the "pre-release" version. Let me know how this would work.

**Comment by rekram1-node** [comment]
@anthdm Are you saying you want merges to master to be pre-releases and then actual releases would be done manually or by a more discriminatory method? Perhaps I misunderstood what you said...

**Comment by rekram1-node** [comment]
Well the simplest option imo are merges to master create a new versioned release, easily done with github actions and goreleaser, simple mock up missing the filler:

name: releaser

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - name: Set up Go
      - name: Tag Release
      - name: Publish Release

**Comment by rekram1-node** [comment]
@anthdm I opened a PR you can look at: https://github.com/anthdm/hollywood/pull/20 lmk if you have any concerns
