### ISSUE TITLE
[Suggestion] Using deadletter instead of engine directly in Registry

### ISSUE THREAD

**Issue by igumus** [anthdm/hollywood#37]
Hi @anthdm,

`Registry` struct in `registry.go` file;

Instead of depending to `*Engine` directly to acquire `deadletter` (which is a Processer), we can directly pass it like;
```
type Registry struct {
	lookup *safemap.SafeMap[string, Processer]
        deadletter Processer
}

func newRegistry(deadletter Processer) *Registry {
	return &Registry{
                deadletter: deadletter,
		lookup: safemap.New[string, Processer](),
	}
}
func (r *Registry) get(pid *PID) Processer {
	if proc, ok := r.lookup.Get(pid.ID); ok {
		return proc
	}
	return r.deadLetter
}
```

If you approve, I like to update it.

**Comment by anthdm** [comment]
Go ahead! Thank you

**Comment by igumus** [comment]
Thanks for your reply. I will add commit to previously open PR (#36).

**Comment by igumus** [comment]
Done 👍

**Comment by anthdm** [comment]
@igumus Where you working on this?

**Comment by igumus** [comment]
After you approved changes that I suggest, PR changes in #36 .

**Comment by anthdm** [comment]
@igumus aha I see. Thanks for that my man!
