### ISSUE TITLE
using QUIC and queuing question?

### ISSUE THREAD

**Issue by lonnietc** [anthdm/hollywood#39]
Hello All,

I am new to the Actor Model engine but I think that I have a rough idea as to what it is and how it works. (still learning though)

I am building out a massively scaling P2P project (Windows 10 x86) and for each node I was thinking to have type of Hollywood node that would receive messages, queue them if needed, and process them from the queue in-turn.  It seems that Hollywood might be able to handle this with great success from what I have seen so far with the benchmarks and running some of the examples although I still need to investigate and get some guidance more on this.

The other thing that I am wondering about is if there any examples of Hollywood using QUIC like you have in the examples/tcpserver or similar. Are there any examples or ideas on how this might be achieved?

Thanks and have a great day

**Comment by anthdm** [comment]
The TCP server example should give you a good head start.
