### ISSUE TITLE
examples/tcpserver goroutine leak

### ISSUE THREAD

**Issue by sansayin** [anthdm/hollywood#40]
the tcpserver (examples/tcpserver) crashed during the stress test.
gorutines number will not reduce after the tcp client disconnected.

**Comment by anthdm** [comment]
Thanks for reporting will look into this.

**Comment by anthdm** [comment]
We had a memory look with the old GGQ implementation. I replaced this with a new stable ring buffer. Let me know if this issue still persist. Closing this for now. Feel free to re-open whenever.
