### ISSUE TITLE
ACTOR KEEPS CRASHING: "runtime error: index out of range [1025] with length 1025" 

### ISSUE THREAD

**Issue by Sijibomii** [anthdm/hollywood#42]
The actor panics at random intervals and I can't figure out why. From the stacktrace, it seems to be an issue with the ggq/ggq.go file. Any help will be much appreciated!

<img width="739" alt="Screen Shot 2023-07-14 at 6 03 34 AM" src="https://github.com/anthdm/hollywood/assets/73986352/fa74f3a8-109d-4c84-b2c0-4880dc20e1c8">

**Comment by BlizzTom** [comment]
You have to set a larget inbox when spawning

This is what we did, and have a const for a bigger inbox (8192).

```go
actor.WithInboxSize(batch.InboxSize)
```

**Comment by anthdm** [comment]
Fixed this by replacing ggq with new ring buffer
