### ISSUE TITLE
Memory leak with inboxes

### ISSUE THREAD

**Issue by BlizzTom** [anthdm/hollywood#43]
First of all, great concept library! I recently used it in a quick tool I needed, so figured I would stretch the legs a bit.

What I discovered, is that in a roughly 200 actor system with 8k inboxes and a rough inbox rate of 1-100 messages per actor per second, after about 8 hours the application would be consuming around 2gb of memory.

I did quite a bit of profiling, and at first guess, things that are going into the ggq, are not getting garbage collected at all.

I copied the lib into my application, swapped out the inbox ggq implementation with a channel, and the memory leak disappeared.

Sorry I didn't spend much more time on digging deeper than that, needed to get that tool stable.

I was able to replicate this consistently over the last week, with the same load, about 8 hours in, my app would be near 2gb of memory, with a slow climb nearing the same size of the messages going in.

**Comment by anthdm** [comment]
@BlizzTom Thank you for reporting this. I'm going to look into this right away. I must admit that the GGQ is kinda experimental and needs some deeper profiling and probably rework.

**Comment by anthdm** [comment]
This should be fixed. Replaced the old queue with a stable ring buffer implementation.

**Comment by anthdm** [comment]
Closing this to keep things clean. Feel free to re-open any time if you still encounter issues.
