### ISSUE TITLE
Hollywood speeds

### ISSUE THREAD

**Issue by lonnietc** [anthdm/hollywood#48]
Hello,

I am looking over many libraries for this P2P project and I think that Hollywood could be an awesome solution, but have a few questions that I hope you will answer for me.

Some similar libraries seems to be:

Hollywood
libp2p-go
ZeroMQ

At the core of the project idea is that this will be a massive P2P database such that maybe each node will have an SQLite (or maybe Immudb) and/or some KV instance running and the nodes can pass data in message blocks as needed.  Data can be relayed through node neighborhoods to other nodes that are not in the neighborhood to reach their destination.

Effectively the user may be able to write data globally or locally which will also be encrypted to the network without having to worry about where the data is stored but know that it is encrypted and striped across nodes like you might find in various RAID levels.

Although I am still researching this idea, I think that message passing may be the best approach but also need the fastest and most reliable core to start with and although Libp2p offers node discovery, I think that just maybe Hollywood or ZeroMQ that I do not think have node discovery could be much faster, but could be wrong.

Any ideas or thoughts on this?

Thanks

**Comment by lonnietc** [comment]
Just a update to this question, but what would it take for Hollywood have node discovery so that it could find other hollywood instances?

That would be very useful for what I am doing.

Thanks again

**Comment by anthdm** [comment]
Node discovery is something that is on the planning for a long time. This is not yet implemented (as you already know), but, I will start that first foundation of that implementation very soon. Maybe even this week already.

**Comment by lonnietc** [comment]
Thanks for the information on this and I am working out some details to see how things can come together, my friend.

Have a great day
