### ISSUE TITLE
cluster support

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#53]
I'm curious about what is meant with "Cluster support [coming soon]"? What would it enable that is currently not possible.

TIA, Per.

**Comment by perbu** [comment]
To paraphrase discussion on discord, cluster support mostly means two things.
- service discovery, ie, a way for a node to discover the other nodes working together in the system
- some sort of actor directory, ie for a node to know what actors are remotely available.

**Comment by perbu** [comment]
After thinking a bit about it, I think this is really hard. Initially I thought about having an actor which would have a magical name and then having actors send messages here when they are spawned and stopped. This sounds simple enough.

But I'm not at all sure how to deal with things like a node going entirely offline. And, if we can't deal with that situation, is there any point to have a registry?

**Comment by anthdm** [comment]
In able to have 100% uptime on the cluster we need to have a third party dependency like Consul.

**Comment by anthdm** [comment]
First draft is landed on the master
