### ISSUE TITLE
Import Error: package log/slog not in GOROOT (/usr/local/go/src/log/slog)

### ISSUE THREAD

**Issue by mtmibjas** [anthdm/hollywood#57]
I'm encountering an issue while importing the package `github.com/anthdm/hollywood/log`. The error message suggests that the package `log/slog` is not found in GOROOT (/usr/local/go/src/log/slog).

**Environment:**
- Go version: 1.19
- Operating System: mac os

**Error Message:**
error while importing github.com/anthdm/hollywood/log: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)

**Comment by mtmibjas** [comment]
@AR1011 i updated to Go Version 1.21.4 but still I am facing same error.

**Comment by AR1011** [comment]
@mtmibjas 

What is the output of this in the terminal ?
```bash
go version
```
