### ISSUE TITLE
What is missing to progress to a stable production release? AKA 1.0

### ISSUE THREAD

**Issue by anthdm** [anthdm/hollywood#59]

**Comment by perbu** [comment]
I think the only thing I'm currently missing is some sort of registry that would allow me to keep track of remote actors. I'm not sure if it should be an example or if it should be something native to the library. I'm fine either way, but a documented way of discovering and tracking remote actors would be good, especially for ppl without much experience with the actor model.

Also, _maybe_ it is a good idea to keep it at 0.X versions for the first year or so? Just so we can alter the API if we need to without having to add a v2.

**Comment by perbu** [comment]
One more thing. I noticed some constants around, which seem like they should be tunable. If the engine initialization would use the functional option pattern, it would be an improvement. Today's solution it feels a bit rushed. I'm quite a bit familiar with those bits now, so I can lend a hand. Just assign me a task if you want me to take care of it. At least I can start, but I'm unsure about what tunables to expose.

Also, I noticed the safemap package. Is there a reason for not using sync.Map for this? sync.Map should remove the inherit scalability issues with a mutex-guarded map. Again, I don't mind doing this. Just assign me the task

**Comment by anthdm** [comment]
@perbu Feel free to start on any of the things you mentioned. You can create an issue for that. I will assign you if you cant assign yourself. Feel free to use your gut feeling.

Again, thanks for the effort, much appreciate it.

**Comment by perbu** [comment]
There are still a few TODOS. Some are like this:
```
func (pid *PID) HasTag(tag string) bool {
	panic("TODO")
}
```

**Comment by anthdm** [comment]
@perbu We might need a timeline?
