### ISSUE TITLE
How to make sure all messages are sent

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#60]
I'm polishing up the chat example, adding some logging and fixing some issues. One thing I've noticed is that the disconnect event doesn't reach the server when the client shuts down.

I can ofc add a time.Sleep(), but that would be lame.

How do I flush out all messages so we can shutdown cleanly?

**Comment by anthdm** [comment]
@perbu Going to look into it right now.

**Comment by anthdm** [comment]
@perbu In progress https://github.com/anthdm/hollywood/pull/69

**Comment by anthdm** [comment]
#69
