### ISSUE TITLE
How to directly stop an actor?

### ISSUE THREAD

**Issue by noahsilverman** [anthdm/hollywood#65]
We can send a Poison message to any actor, but that won't immediately kill the actor. 

What if we want to immediately stop the actor, ignoring all messages in the queue?

**Comment by anthdm** [comment]
@noahsilverman That's a good question! That is something that needs to be coded in.

I was thinking of a `Stop` message. We could call it with `Stop(pid)` instead of `Poision(pid)`

Will try to add that in today for you.

**Comment by noahsilverman** [comment]
@anthdm I appreciate it!  Once I'm more familiar with the code base, I don't mind helping to contribute .  (Still learning how all the internals are organized)

**Comment by anthdm** [comment]
close by #69
