### ISSUE TITLE
Actor subscribe to event stream

### ISSUE THREAD

**Issue by noahsilverman** [anthdm/hollywood#66]
It would be awesome if any actor could subscribe to the global event stream This could become a nice broadcast/signalling channel for all running children.

The challenge is: how to access it.

In the eventStream example, the code subscribes directly to the event stream by calling a function of the engine.  However, a child only knows its own PID, and does not have direct access to the engine.

One awkward way would be to subscribe when the Receiver gets a `started` message:
```
func (state *a) Receive(ctx *actor.Context) {

	switch msg := ctx.Message().(type) {

	case *actor.Started:
		ctx.Engine().EventStream.Subscribe(...)
}
```

Is this good enough, or do we want something more specific?

**Comment by anthdm** [comment]
@noahsilverman Do you mean that you want the event stream to be available on every actor magically, without subscribing to it first?

**Comment by noahsilverman** [comment]
@anthdm Not magically.  I Just thought it would be nice if there was an easy (or direct) way for any actor to subscribe or publish to eventStream.

When I've built actor-based systems in Erlang, I always had some kind of global notification process running.  So, any actor could publish "announcement", and any actor could optionally listen for global events.

Subscribing, during the actor.Started message, works.  But feels a bit awkward.

**Comment by anthdm** [comment]
@noahsilverman I understand what you are saying. Let me think of a good way to handle that.

**Comment by noahsilverman** [comment]
Please let me know if I can help

**Comment by perbu** [comment]
I have a resonably good grip on this. I'll make sure it is documented.

**Comment by perbu** [comment]
@noahsilverman could you review the PR mentioned above and see if you think I've hit the spot?
