### ISSUE TITLE
Remove redis dependency

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#68]
The examples pollute the go.mod file a bit. If we keep adding examples, the go.mod file will bloat further.
suggest name: hollywood-examples.

**Comment by anthdm** [comment]
We should keep the examples in the main repo. Examples that have other dependencies, like Redis, should have a go mod file?

**Comment by nrhvyc** [comment]
The Go binaries won't include these examples during compilation. Having easily available examples may help adoption.

**Comment by perbu** [comment]
@anthdm Having a go.mod file isn't great. We had that on one example (mdns). The problem is that it locks on to a specific version of Hollywood. Less of a problem if we stop changeing master as much as we've done lately.

If this was an application I'd be less concerned about the size of the go.mod, but as it's a framework, it'll be pulled into many, many applications (at least that is the goal).

There are currently two examples that add things to the go.mod-file: 
1) Redis.

I think I can change this just to use file IO and kick the dependency that way. The semantics will be the same, will probably improve the value of the example as you wouldn't need Redis to run the thing.

2) mdns, adds dep on zeroconf. This example is really quite cool and might actually be something we wanna have inside hollywood. Having a cluster autoconfigure itself by multicast DNS rather than be finding an existing node is really useful.

**Comment by anthdm** [comment]
@perbu Agreed here. So I will update the "Persistance middleware example" to use something more simple (inmem). Like you mentioned the semantics will be the same. 

Regarding zeroconf, that is something that will be available inside the cluster once that update is merged.

**Comment by perbu** [comment]
Ok. I've re-scoped the issue to reflect the discussion. I can do the work so I've assigned myself to the issue.

The zeroconf depency will likely stay as @anthdm seem to like the idea of using it for service discovery.
