### ISSUE TITLE
Message Initialized{} seems to be unused.

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#70]
From my testing I've never seem to get the Initialized{} message when I spin up an actor. I get the Started{} and Stopped{}.

Is this an oversight or am I missing something?

Per.

**Comment by anthdm** [comment]
@perbu You are 100% right. This message is unused. I though this would be a good addition back in the beginning but I changed my mind, I guess. There is not really much benefit to gain from the Initialized method. We can remove that.

**Comment by anthdm** [comment]
@perbu I removed it in the graceful PR

**Comment by anthdm** [comment]
@perbu just realized we do use it. in `process.Start()`

**Comment by perbu** [comment]
Yeah. I saw that it was used there, but AFAIK I don't think these messages are being delivered to the actors. Might be me messing up, however, I'm not certain.

**Comment by tralafiti** [comment]
@perbu `Initialized{}` is delivered to the actor one line below it's usage: https://github.com/anthdm/hollywood/blob/master/actor/process.go#L127

I do use it a lot to setup slogs with actor specific attributes and it works just fine here

**Comment by perbu** [comment]
This is all correct. For some reason I seems to have missed it. This works as advertised. Good feedback from @tralafiti, stating it is useful.
