### ISSUE TITLE
Idea; replace logging with an system event actor

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#77]
We'ce had this discussion, which was quite interesting.

Logging is a bit ugly. But having debug messages, system events and failures accessible somewhere is important for production use.

So, we should think about ripping out the logging and replacing it with a system event actor. This could look roughly like this:

We define a type SystemEvent, similar to a DeadletterEvent{}. It shoud have the following fields

- source (string?)
- message (string)
- severity (debug, info, warning, error)
- key/value set for arbitrary fields (are there performance implications here? - perhaps it should be a slice, like slog uses that will avoid the overhead of creating a map

Now, when something happens, where we currently log something, a SystemEvent message is sent to the actor. Out of the box Hollywood can ship with a simple actor which just logs these messages to stdout.

System events we want to handle:
- actor started or stopped
- remote started or stopped
- cluster activation event
- cluster deactivation event
- cluster member join
- cluster member leave

Now, if a user wants to handle these messages in a custom way the user can just supply an actor and do whatever they please with it.

**Comment by anthdm** [comment]
@perbu I'm going to cook up a complete refactor of the event stream. Will do that first in favor of the cluster package, cause its very depending on that.

**Comment by anthdm** [comment]
@perbu New event stream is merged into master. The stage is yours.

**Comment by anthdm** [comment]
@perbu I would also suggest to completely remove the log package and just (where we want) use slog.

**Comment by anthdm** [comment]
@perbu we can close this right?
