### ISSUE TITLE
Kill the global variable 'pidSeparator'

### ISSUE THREAD

**Issue by perbu** [anthdm/hollywood#90]
the pidSeparator is a global variable. we should get rid of it and either:
- replace it with a hard-coded const "/".
- replace it with a struct variable on the engine (which is a tad bit harder)

We should also document that you cannot use pid separator in actor names and check that the supplied actor name doesn't contain a /.

this is a good first task.

**Comment by anthdm** [comment]
@perbu This pidSepator is used all over the place I recommend making it const and never configurable.

**Comment by perbu** [comment]
As long as it ain't a global variable I'm happy.

**Comment by julian776** [comment]
Hi,

You expect something like: 

```go
const (
	PID_SEPARATOR = "/"
)
```

**Comment by anthdm** [comment]
@julian776 I think this is already addressed in one of my previous commits.
